name: neuro-gru-cue-topology
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy==2.3.5
      - pandas==2.2.3
      - matplotlib==3.10.8
      - torch==2.10.0
      - scikit-learn==1.8.0
      - ripser==0.6.15
      - persim==0.3.8
      - jupyterlab==4.5.3
      - ipykernel==7.2.0
